# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-27 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('nirf', models.CharField(blank=True, max_length=12, null=True)),
                ('incra', models.CharField(blank=True, max_length=12, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('nome_contato', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'propriedades',
                'verbose_name': 'propriedade',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='PropriedadeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('ativo', models.BooleanField(default=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedades.Propriedade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'propriedades_users',
                'verbose_name': 'propriedade_user',
            },
        ),
    ]
