# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
