# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_auto_20180727_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.SmallIntegerField(choices=[(None, '---'), (1, 'macho'), (2, 'fêmea')], verbose_name='Sexo')),
                ('brinco', models.CharField(max_length=25, verbose_name='Brinco')),
                ('nascimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('entrada', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrada no Estoque')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída do Estoque')),
                ('motivo_saida', models.SmallIntegerField(blank=True, choices=[(None, '---'), (1, 'venda'), (2, 'troca'), (3, 'abate'), (4, 'morte'), (5, 'outros')], null=True, verbose_name='Motivo da saída')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedades.Propriedade')),
            ],
            options={
                'verbose_name_plural': 'animais',
                'verbose_name': 'animal',
            },
        ),
        migrations.CreateModel(
            name='AnimalPesagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('peso', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Peso')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedades.Animal')),
            ],
            options={
                'verbose_name_plural': 'pesagens',
                'verbose_name': 'pesagem',
            },
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together=set([('propriedade', 'brinco')]),
        ),
    ]
