# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0003_auto_20180728_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalpesagem',
            options={'ordering': ('-data',), 'verbose_name': 'pesagem', 'verbose_name_plural': 'pesagens'},
        ),
    ]
